config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testnotebook-sqaaas:
      branch: main
      repo: https://github.com/PalomoIFCA/testnotebook-sqaaas
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-emerald-earwig.sh
        container: qc.acc_homey-firebrick-argentino
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-apricot-avocet.sh
        container: qc.doc_droopy-cinnamon-maltese
      github.com/PalomoIFCA/testnotebook-sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-taupe-moose.sh
        container: qc.doc_goopy-sapphire-mammoth
      github.com/PalomoIFCA/testnotebook-sqaaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-flax-goat.sh
        container: qc.doc_boozy-dandelion-chinchilla
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-pumpkin-vole.sh
        container: qc.lic_lanky-goldenrod-eagle
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-cyan-dalmatian.sh
        container: qc.sec_bluesy-ecru-lobster
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-chartreuse-hippopotamus.sh
        container: qc.sty_zippy-razzmatazz-cuscus
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas pytest:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-platinum-cheetah.sh
        container: qc.uni_gamy-violet-sheepdog
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-bistre-bulldog.sh
        container: qc.ver_goopy-olive-manatee
timeout: 5400
