config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testnotebook-sqaaas:
      branch: main
      repo: https://github.com/PalomoIFCA/testnotebook-sqaaas
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-ecru-ray.sh
        container: qc.acc_wheezy-emerald-ladybird
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-orchid-salamander.sh
        container: qc.doc_cranky-bronze-chinchilla
      github.com/PalomoIFCA/testnotebook-sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-cornflower-dollar.sh
        container: qc.doc_pasty-firebrick-gopher
      github.com/PalomoIFCA/testnotebook-sqaaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-cerulean-sheepdog.sh
        container: qc.doc_stinky-saffron-frise
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-sapphire-salamander.sh
        container: qc.lic_chewy-xanthic-dormouse
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-orchid-lion.sh
        container: qc.sec_crappy-aquamarine-emu
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-puce-falcon.sh
        container: qc.sty_dorky-magenta-tiger
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas pytest:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-chocolate-chinook.sh
        container: qc.uni_slimy-harlequin-squirrel
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-lime-tarsier.sh
        container: qc.ver_scummy-sapphire-tapir
timeout: 5400
