config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testnotebook-sqaaas:
      branch: main
      repo: https://github.com/PalomoIFCA/testnotebook-sqaaas
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-amaranth-tetra.sh
        container: qc.acc_flabby-burgundy-elephant
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-pink-sheepdog.sh
        container: qc.doc_grumpy-ecru-beaver
      github.com/PalomoIFCA/testnotebook-sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-cobalt-caterpillar.sh
        container: qc.doc_slimy-saffron-fousek
      github.com/PalomoIFCA/testnotebook-sqaaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-eggplant-shrew.sh
        container: qc.doc_silly-salmon-paradise
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-razzmatazz-dalmatian.sh
        container: qc.lic_cheeky-celadon-shrimp
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-wheat-moose.sh
        container: qc.sec_baggy-scarlet-terrier
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-alizarin-meerkat.sh
        container: qc.sty_snoopy-persimmon-bandicoot
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas pytest:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-brass-ragdoll.sh
        container: qc.uni_jumpy-yellow-zebu
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-alizarin-dragonfly.sh
        container: qc.ver_jumpy-mauve-kangaroo
timeout: 5400
