config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testnotebook-sqaaas:
      branch: main
      repo: https://github.com/PalomoIFCA/testnotebook-sqaaas
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-zucchini-labradoodle.sh
        container: qc.acc_randy-mauve-wolfhound
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-fuchsia-numbat.sh
        container: qc.doc_wheezy-sepia-dachsbracke
      github.com/PalomoIFCA/testnotebook-sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-seashell-vole.sh
        container: qc.doc_skimpy-bistre-guppy
      github.com/PalomoIFCA/testnotebook-sqaaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-bronze-bat.sh
        container: qc.doc_bumpy-ultramarine-kudu
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-champagne-kingfisher.sh
        container: qc.lic_droopy-taupe-monster
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-lemon-chin.sh
        container: qc.sec_nippy-salmon-gharial
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-pumpkin-chameleon.sh
        container: qc.sty_paltry-ultramarine-tang
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas pytest:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-razzmatazz-manatee.sh
        container: qc.uni_lousy-emerald-shrew
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-cinnamon-schnauzer.sh
        container: qc.ver_muzzy-crimson-havanese
timeout: 5400
