config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testnotebook-sqaaas:
      branch: main
      repo: https://github.com/PalomoIFCA/testnotebook-sqaaas
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-teal-lizard.sh
        container: qc.acc_zippy-firebrick-beagle
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-apricot-fish.sh
        container: qc.doc_greasy-saffron-beaver
      github.com/PalomoIFCA/testnotebook-sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-lime-ferret.sh
        container: qc.doc_blurry-charcoal-lobster
      github.com/PalomoIFCA/testnotebook-sqaaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-brass-penguin.sh
        container: qc.doc_greasy-puce-termite
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-cinnamon-jaguar.sh
        container: qc.lic_snazzy-periwinkle-zorse
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-bistre-mule.sh
        container: qc.sec_snoopy-apricot-mayfly
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-maroon-walrus.sh
        container: qc.sty_queasy-asparagus-mau
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas pytest:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-tan-crab.sh
        container: qc.uni_frumpy-champagne-iguana
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-yellow-bee.sh
        container: qc.ver_woozy-pear-fly
timeout: 5400
