config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testnotebook-sqaaas:
      branch: main
      repo: https://github.com/PalomoIFCA/testnotebook-sqaaas
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-aqua-wolverine.sh
        container: qc.acc_jumpy-scarlet-neanderthal
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-salmon-moorhen.sh
        container: qc.doc_sleazy-rust-dodo
      github.com/PalomoIFCA/testnotebook-sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-dandelion-markhor.sh
        container: qc.doc_scummy-chartreuse-centipede
      github.com/PalomoIFCA/testnotebook-sqaaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-malachite-balinese.sh
        container: qc.doc_sleazy-amber-tuatara
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-grey-boar.sh
        container: qc.lic_freaky-ecru-eagle
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-vermilion-goose.sh
        container: qc.sec_slaphappy-cream-avocet
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-zucchini-avocet.sh
        container: qc.sty_dorky-saffron-nightingale
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas pytest:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-plum-quetzal.sh
        container: qc.uni_sleepy-russet-chicken
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-russet-swan.sh
        container: qc.ver_flimsy-lilac-falcon
timeout: 5400
