config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testnotebook-sqaaas:
      branch: main
      repo: https://github.com/PalomoIFCA/testnotebook-sqaaas
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-fuchsia-devil.sh
        container: qc.acc_stinky-cerulean-kangaroo
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-flax-chipmunk.sh
        container: qc.doc_ugly-beige-rottweiler
      github.com/PalomoIFCA/testnotebook-sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-puce-affenpinscher.sh
        container: qc.doc_goopy-cream-butterfly
      github.com/PalomoIFCA/testnotebook-sqaaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-cornflower-bullfrog.sh
        container: qc.doc_crappy-amber-reindeer
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-linen-chimpanzee.sh
        container: qc.lic_jumpy-silver-dogfish
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-magenta-jackal.sh
        container: qc.sec_stuffy-firebrick-mastiff
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-peach-eel.sh
        container: qc.sty_sloppy-cerise-hyrax
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas pytest:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-tan-akbash.sh
        container: qc.uni_nerdy-maroon-starfish
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-lavender-bullfrog.sh
        container: qc.ver_shaky-celadon-chameleon
timeout: 5400
