config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testnotebook-sqaaas:
      branch: main
      repo: https://github.com/PalomoIFCA/testnotebook-sqaaas
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-azure-alligator.sh
        container: qc.acc_lousy-cardinal-capuchin
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-razzmatazz-cassowary.sh
        container: qc.doc_blurry-wisteria-yak
      github.com/PalomoIFCA/testnotebook-sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-amethyst-hummingbird.sh
        container: qc.doc_muzzy-ecru-akbash
      github.com/PalomoIFCA/testnotebook-sqaaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-sapphire-chow.sh
        container: qc.doc_slaphappy-vermilion-tang
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-scarlet-frigatebird.sh
        container: qc.lic_slaphappy-turquoise-leopard
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-cinnabar-owl.sh
        container: qc.sec_gloppy-dandelion-greyhound
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-khaki-chihuahua.sh
        container: qc.sty_scanty-cinnabar-chicken
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-fuchsia-havanese.sh
        container: qc.uni_baggy-smalt-jellyfish
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-cyan-bongo.sh
        container: qc.ver_snappy-cobalt-akita
timeout: 5400
