config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testnotebook-sqaaas:
      branch: main
      repo: https://github.com/PalomoIFCA/testnotebook-sqaaas
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-yellow-antelope.sh
        container: qc.acc_frumpy-chartreuse-audemer
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-orchid-eagle.sh
        container: qc.doc_nippy-flax-seahorse
      github.com/PalomoIFCA/testnotebook-sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-tan-bird.sh
        container: qc.doc_chummy-pear-shrimp
      github.com/PalomoIFCA/testnotebook-sqaaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-chestnut-bullfrog.sh
        container: qc.doc_flaky-charcoal-mongoose
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-khaki-tuatara.sh
        container: qc.lic_snoopy-aquamarine-bobcat
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-harlequin-monster.sh
        container: qc.ver_zippy-brass-owl
timeout: 5400
