config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testnotebook-sqaaas:
      branch: main
      repo: https://github.com/PalomoIFCA/testnotebook-sqaaas
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-magnolia-armadillo.sh
        container: qc.acc_muzzy-chestnut-budgerigar
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-turquoise-lion.sh
        container: qc.doc_skimpy-saffron-wallaby
      github.com/PalomoIFCA/testnotebook-sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-asparagus-ladybird.sh
        container: qc.doc_stuffy-alizarin-mastiff
      github.com/PalomoIFCA/testnotebook-sqaaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-chestnut-fish.sh
        container: qc.doc_lovely-eggplant-havanese
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-pear-okapi.sh
        container: qc.lic_scanty-cinnabar-lobster
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-viridian-badger.sh
        container: qc.sec_crabby-viridian-tamarin
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-wheat-squirrel.sh
        container: qc.sty_gloppy-turquoise-abyssinian
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas pytest:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-razzmatazz-dalmatian.sh
        container: qc.uni_flabby-lilac-akbash
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-myrtle-wildebeest.sh
        container: qc.ver_sunny-denim-sparrow
timeout: 5400
