config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testnotebook-sqaaas:
      branch: main
      repo: https://github.com/PalomoIFCA/testnotebook-sqaaas
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-cyan-wolfhound.sh
        container: qc.acc_flimsy-denim-wrasse
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-corn-axolotl.sh
        container: qc.doc_craggy-salmon-whippet
      github.com/PalomoIFCA/testnotebook-sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-coral-llama.sh
        container: qc.doc_flimsy-tomato-setter
      github.com/PalomoIFCA/testnotebook-sqaaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-mustard-chicken.sh
        container: qc.doc_blurry-salmon-ladybird
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-cerise-dhole.sh
        container: qc.lic_leaky-olive-abyssinian
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-saffron-gopher.sh
        container: qc.sec_hasty-brass-wombat
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas flake8:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-alizarin-shrew.sh
        container: qc.sty_smelly-cornflower-shrew
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-aqua-zebra.sh
        container: qc.uni_tacky-lavender-barracuda
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testnotebook-sqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-fuchsia-barracuda.sh
        container: qc.ver_gloppy-wisteria-cheetah
timeout: 5400
